import Head from "next/head";

import { api } from "~/utils/api";
import { useState } from "react";
import { motion } from "framer-motion";
import {
  Button,
  Frame,
  GroupBox,
  Hourglass,
  Window,
  WindowContent,
  WindowHeader,
} from "react95";
import Image from "next/image";

export default function Character() {
  const { data, isLoading } = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="flex h-full w-full flex-col items-center justify-center p-6 sm:h-auto "
        >
          {isLoading ? (
            <Hourglass size={48} />
          ) : (
            <Window
              className={
                "h-full w-full max-w-4xl !bg-zinc-900/70 backdrop-blur-md"
              }
            >
              <WindowHeader className={"flex justify-between"}>
                <span>adventure.exe</span>
                <Button>X</Button>
              </WindowHeader>
              <WindowContent className="flex h-full flex-col justify-between gap-2 !px-0 !pb-8 sm:!pb-0">
                <div className="flex flex-col items-center !overflow-y-auto px-2 sm:flex-row sm:justify-evenly">
                  <GroupBox label="Jessica">
                    <Frame>
                      <div className="w-25 flex flex-col items-center justify-center">
                        <Image
                          src="/chelsea.jpg"
                          width={200}
                          height={200}
                          alt="character"
                        />
                        <p className="text-center">
                          Ava, a middle-class cyberpunk hacker, navigates
                          dystopian cityscapes with technical prowess and
                          rebellion in her veins, seeking justice for her
                          family's corporate exploitation.
                        </p>
                        <Button>
                          <span className="text-black">select</span>
                        </Button>
                      </div>
                    </Frame>
                  </GroupBox>
                  <GroupBox label="Jessica">
                    <Frame>
                      <div className="w-25 flex flex-col items-center justify-center">
                        <Image
                          src="/chelsea.jpg"
                          width={200}
                          height={200}
                          alt="character"
                        />
                        <p className="text-center">
                          Leon, a wealthy cyberpunk scion, hides deep family
                          trauma—his parents' ruthless corporate feuds led to a
                          tragic accident, leaving him with survivor's guilt and
                          a relentless pursuit of vengeance.
                        </p>
                        <Button>
                          <span className="text-black">select</span>
                        </Button>
                      </div>
                    </Frame>
                  </GroupBox>
                  <GroupBox label="Jessica">
                    <Frame>
                      <div className="w-25 flex flex-col items-center justify-center">
                        <Image
                          src="/chelsea.jpg"
                          width={200}
                          height={200}
                          alt="character"
                        />
                        <p className="text-center">
                          Zara, a fugitive cyberpunk with illicit body mods,
                          evades authorities for black-market enhancements.
                          Self-serving by nature, she reluctantly protects a
                          vulnerable ward, indebted by a past favor.
                        </p>
                        <Button>
                          <span className="text-black">select</span>
                        </Button>
                      </div>
                    </Frame>
                  </GroupBox>
                </div>
                <Button variant="default" className="w-1">
                  <span className="text-black">next</span>
                </Button>
              </WindowContent>
            </Window>
          )}
        </motion.div>
      </main>
    </>
  );
}
