import Head from "next/head";

import { api } from "~/utils/api";
import {
  AppBar,
  Button,
  Hourglass,
  MenuList,
  MenuListItem,
  Separator,
  TextInput,
  Toolbar,
  Tooltip,
  Window,
  WindowContent,
  WindowHeader,
} from "react95";
import { motion } from "framer-motion";
import { useState } from "react";
import router from "next/router";



interface Message {
  text: string;
  isPlayer: boolean;
}



export default function desktopScreen() {
  
  const[iconClicked, setIconClicked] = useState(0);

  const handleSwitch = (newValue:any) => {
    // Update the state when the button is clicked
    setIconClicked(newValue);
  };

  
  

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="flex h-full w-full flex-col p-6"
        >

      {iconClicked === 0 && (
        <div className="mt-20">
           <Tooltip text='Customization' enterDelay={100} leaveDelay={200}>
              <button onClick={() => handleSwitch(1)}>
                  <img className="m-2"
                  src="/ComputerIcon.png"
                  alt="Example Image"
                  width={100}  // Set the width of the image
                  height={100} // Set the height of the image
                  />
              </button>
         </Tooltip>
             
            <Tooltip text='Secret' enterDelay={100} leaveDelay={200}>
            <button onClick={() => handleSwitch(2)}>
                  <img className="m-2"
                  src="/FolderIcon.png"
                  alt="Example Image"
                  width={100}  // Set the width of the image
                  height={100} // Set the height of the image
                  />
              </button>
         </Tooltip>
          
      

          <div className="absolute bottom-10 left-10  ...">
            <Tooltip text='Recycle‍' enterDelay={100} leaveDelay={200}>
            <button onClick={() => handleSwitch(3)}>
                 <img className="m-2"
                  src="/RecycleIcon.png"
                  alt="Example Image"
                  width={100}  // Set the width of the image
                  height={100} // Set the height of the image
                  />
                </button>
            </Tooltip>
         </div>
            
        </div>
        )}

        {iconClicked === 1 && (
          <div className="m-20  "> 
           <motion.div
           initial={{ opacity: 0 }}
           animate={{ opacity: 1 }}
           className="flex h-full w-full flex-col p-6"
         >
          <Window
            className={
              "h-full w-full max-w-4xl !bg-zinc-900/70 backdrop-blur-md"
            }
          >
            <WindowHeader className={"flex select-none justify-between"}>
              <span>adventure.exe</span>
              <Button onClick={() => void router.push("/")}>X</Button>
            </WindowHeader>
            <WindowContent
              className={"flex h-full flex-col justify-end gap-4 !pb-8"}
            >
              

             
            </WindowContent>
          </Window>
            </motion.div>
            </div>
        )}

        {iconClicked === 2 && (
          <div className="m-30">1</div>
        )}

        {iconClicked === 3 && (
          <div className="m-200">1</div>
        )}



    <div className="absolute bottom-10 left-10  ...">
        <AppBar>
      <Toolbar style={{ justifyContent: 'space-between' }}>
        <div style={{  display: 'inline-block' }}>
            <Button>
            Start
          </Button>
        </div>
        <TextInput placeholder='Search...' width={150} />
      </Toolbar>
    </AppBar>
    </div>

        </motion.div>
      </main>
    </>

  );
}
