import Head from "next/head";

import { api } from "~/utils/api";
import {
  Button,
  Hourglass,
  Window,
  WindowContent,
  WindowHeader,
} from "react95";
import { motion } from "framer-motion";
import { useState } from "react";

interface Message {
  text: string;
  isPlayer: boolean;
}

export default function desktopScreen() {
  
  
  

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="flex h-full w-full flex-col p-6"
        >

        <div className="grid grid-cols-2 gap-4">
            <div>
                <img className="m-2"
                src="/chelsea.jpg"
                alt="Example Image"
                width={100}  // Set the width of the image
                height={100} // Set the height of the image
                />
            </div>
            <div>2</div>
            <div>
                <img className="m-2"
                src="/chelsea.jpg"
                alt="Example Image"
                width={100}  // Set the width of the image
                height={100} // Set the height of the image
                />
            </div>
            <div>4</div>
            <div>5</div>
            <div>6</div>
            <div>7</div>
            <div>8</div>
           
        </div>
        

        </motion.div>
      </main>
    </>
  );
}
