import Head from "next/head";

import { api } from "~/utils/api";
import {
  Button,
  Hourglass,
  Tooltip,
  Window,
  WindowContent,
  WindowHeader,
} from "react95";
import { motion } from "framer-motion";
import { useState } from "react";

interface Message {
  text: string;
  isPlayer: boolean;
}

export default function desktopScreen() {
  
  
  

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="flex h-full w-full flex-col p-6"
        >

        <div className="mt-10">
           <Tooltip text='Customization' enterDelay={100} leaveDelay={200}>
              <button>
                  <img className="m-2"
                  src="/ComputerIcon.png"
                  alt="Example Image"
                  width={100}  // Set the width of the image
                  height={100} // Set the height of the image
                  />
              </button>
         </Tooltip>
             
            <Tooltip text='Secret' enterDelay={100} leaveDelay={200}>
              <button>
                  <img className="m-2"
                  src="/FolderIcon.png"
                  alt="Example Image"
                  width={100}  // Set the width of the image
                  height={100} // Set the height of the image
                  />
              </button>
         </Tooltip>
           
            <div>
           
            </div>
      

          <div className="absolute bottom-10 left-10  ...">
            <Tooltip text='Recycle‍' enterDelay={100} leaveDelay={200}>
              <button >
                 <img className="m-2"
                  src="/RecycleIcon.png"
                  alt="Example Image"
                  width={100}  // Set the width of the image
                  height={100} // Set the height of the image
                  />
                </button>
            </Tooltip>
         </div>
            
        </div>

        

        </motion.div>
      </main>
    </>
  );
}
