import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen bg-[url('/windowsHeader16-9.png')]">
        <div className="bg-[#140420] opacity-60 w-full h-full">
          <span className="text-white">{hello.data?.greeting}</span>
        </div>
      </main>
    </>
  );
}
