import Head from "next/head";

import { api } from "~/utils/api";
import { useState } from "react";

interface Message {
  text: string;
  isPlayer: boolean;
}

export default function Home() {
  const { data, isLoading } = api.example.hello.useQuery({ text: "from tRPC" });

  const [messages, setMessage] = useState<Message[]>([
    { text: "Hello", isPlayer: true },
    { text: "How are you?", isPlayer: false },
    { text: "What is the best way to do this?", isPlayer: true },
    { text: "Howdy!", isPlayer: false },
    { text: "Yay next.js", isPlayer: true },
  ]);

  
  function exitButton() {
    window.location.href = '/desktopScreen';
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen"></main>
    </>
  );
}
